lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
include: [mods/.index, mods, config, .index]
show_dir_listing: false
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
